FROM chromedp/headless-shell:latest
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      fonts-noto-cjk \
      fontconfig && \
    fc-cache -fv && \
    rm -rf /var/lib/apt/lists/*
